apiVersion: v1
kind: Service
metadata:
  name: "{{.Values.id.app}}"
  labels:
    app: "{{.Values.id.app}}"
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: "{{.Values.id.app}}"