kind: PersistentVolume
apiVersion: v1
metadata:
  name: "{{.Values.id.pv}}"
  labels:
    app: "{{.Values.id.app}}"
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /var/lib/data