apiVersion: v1
kind: Service
metadata:
  name: "{{.Values.id.app}}"
  labels:
    app: "{{.Values.id.app}}"
spec:
  ports:
    - name: "{{.Values.id.app}}"
      port: 5432
      targetPort: 5432
  selector:
    app: "{{.Values.id.app}}"